#!/bin/sh

# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask for password.

RUN="false"
PW1=""
PW2=""
do while ["$PW1" != "$PW2"] || ["$RUN" = "false"];
    db_input high dmx/initial_admin_password || true
    db_go || true
    db_input high dmx/initial_admin_password_again || true
    db_go || true
    db_get dmx/initial_admin_password || true
    PW1="$RES"
    db_get dmx/initial_admin_password_again || true
    PW2="$RES"
    RUN="true"
done
