#!/bin/sh

# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

## Is this a desktop system?
SOCKET_STATUS="$( netstat -lp 2>/dev/null | grep -E 'Xorg|Xwayland' | grep 'X11' )"
PROCESS_STATUS="$( pgrep 'Xorg|Xwayland' )"
if [ -z "${SOCKET_STATUS}" ] && [ -z "${PROCESS_STATUS}" ]; then
    ## prompt headless warning
    db_input high dmx/headless_warning || true
    db_input high dmx/continue_installation || true
    db_go
fi


## Abort installation
db_get dmx/continue_installation
if [ "$RET" = "false" ]; then
    ## Remove my changes to the db.
    db_purge
    exit 0
fi


## Ask for password.
if [ ! -f /etc/dmx/config.properties ]; then
    RUN=''
    PW1=''
    PW2=''
    while [ ! "$RUN" ] || [ "$PW1" != "$PW2" ]; do
        db_input high dmx/initial_admin_password || true
        db_go || true
        db_input high dmx/initial_admin_password_again || true
        db_go || true
        db_get dmx/initial_admin_password || true
        PW1="$RET"
        db_get dmx/initial_admin_password_again || true
        PW2="$RET"
        RUN="true"
    done
fi
