#!/bin/sh
# postinst script for dmx
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

CONFIGFILE='/etc/dmx/config.properties'

# Load config file, if it exists.

### THIS DOES NOT WORK, BECAUSE DMX VARS CONTAIN '.'s.
### if [ -e $CONFIGFILE ]; then
###    . $CONFIGFILE || true
### fi

# Source debconf library.
. /usr/share/debconf/confmodule

### FIXME
### various dirs can be configured via config.properties
### the script should reflect this.

case "$1" in
    configure)

    ## Change password only on initial installation
    if [ -z "$2" ]; then
        ## Get password from debconf-db
        db_get dmx/initial_admin_password
        INITIAL_ADMIN_PASSWORD="$RET"

        cp -a -f $CONFIGFILE $CONFIGFILE.tmp
        sed -e "s/^ *dmx\.security\.initial_admin_password =.*/dmx\.security\.initial_admin_password = $INITIAL_ADMIN_PASSWORD/" \
            < $CONFIGFILE > $CONFIGFILE.tmp
        mv -f $CONFIGFILE.tmp $CONFIGFILE
        db_clear
        echo "Successfuly changed dmx.security.initial_admin_password in /etc/dmx/config.properties."
    fi

    ### Start: Update plugin symlinks
    LINKDIR='/usr/share/dmx/bundle-deploy'
    FILEDIR='/usr/share/dmx/bundle-available'

    ## Create backup dir
    if [ ! -d "${FILEDIR}/.~outdated~" ]; then
        mkdir "${FILEDIR}/.~outdated~"
    fi

    ## Remove conflicting older plugins
    if [ -L ${LINKDIR}/dmx-tableview-command-latest.jar ]; then
        rm ${LINKDIR}/dmx-tableview-command-latest.jar
    fi
    if [ -f ${LINKDIR}/dmx-tableview-command-latest.jar ]; then
        mv ${LINKDIR}/dmx-tableview-command-latest.jar "${FILEDIR}/.~outdated~/"
    fi
    if [ -f ${FILEDIR}/dmx-tableview-command-latest.jar ]; then
        mv ${FILEDIR}/dmx-tableview-command-latest.jar "${FILEDIR}/.~outdated~/"
    fi
    if [ -L ${LINKDIR}/dmx-tableview-command-1.3.0.jar ]; then
        rm ${LINKDIR}/dmx-tableview-command-1.3.0.jar
    fi
    if [ -f ${LINKDIR}/dmx-tableview-command-1.3.0.jar ]; then
        mv ${LINKDIR}/dmx-tableview-command-1.3.0.jar "${FILEDIR}/.~outdated~/"
    fi
    if [ -f ${FILEDIR}/dmx-tableview-command-1.3.0.jar ]; then
        mv ${FILEDIR}/dmx-tableview-command-1.3.0.jar "${FILEDIR}/.~outdated~/"
    fi

    ## Check if there are any files instead of links in $LINKDIR
    PLUGINFILES="$(find "${LINKDIR}/" -maxdepth 1 -name "*.jar" -type f)"
    for pf in ${PLUGINFILES}; do
        ## Extract filename
        filename="$(basename -- "${pf}")"
        plugin="${filename%.*}"
        plugin="$(echo "${plugin}" | sed 's/\-latest//g' | sed -e 's/[0-9].*$//g' | sed 's/\-v$//g'| sed 's/\.v$//g' | sed 's/\-$//g' | sed 's/\.$//g')"
        ## make sure latest file exists in FILEDIR
        cp -u "${pf}" "${FILEDIR}/"
        ## find latest file in filedir
        latestfile="$(ls -rv "${FILEDIR}/${plugin}"*.jar | head -n1)"
        ## update symlink in linkdir
        linkname="$(basename -- "${latestfile}")"
        if [ -f "${LINKDIR}/${linkname}" ]; then
            rm "${pf}"
        fi
        if [ ! -L "${LINKDIR}/${linkname}" ]; then
            ln -s "${latestfile}" "${LINKDIR}/${linkname}"
        fi
    done

    ## Get rid of pluginname-latest.jar files without version number
    ## The whole *-latest.jar should be removed, once they have all been terminated
    PLUGINFILES="$(find "${LINKDIR}/" -maxdepth 1 -name "*-latest.jar" -type l)"
    for lf in ${PLUGINFILES}; do
        ## Extract filename
        filename="$(basename -- "${lf}")"
        plugin="${filename%.*}"
        plugin="$(echo "${plugin}" | sed 's/\-latest//g' | sed -e 's/[0-9].*$//g' | sed 's/\-v$//g'| sed 's/\.v$//g' | sed 's/\-$//g' | sed 's/\.$//g')"
        ## find latest versioned file in filedir
        latestfile="$(ls -rv "${FILEDIR}/${plugin}"*.jar | grep -v '\-latest\.jar' | head -n1)"
        if [ -f "${latestfile}" ]; then
            ## check for *-latest.jar files in filedir
            if [ -f "${FILEDIR}/${plugin}-latest.jar" ]; then
                mv "${FILEDIR}/${plugin}-latest.jar" "${FILEDIR}/.~outdated~/"
            fi
            ## check for *-latest.jar links in linkdir
            if [ -L "${LINKDIR}/${plugin}-latest.jar" ]; then
                rm "${LINKDIR}/${plugin}-latest.jar"
            fi
            ## create new symlink for versioned plugin
            linkname="$(basename -- "${latestfile}")"
            if [ ! -L "${LINKDIR}/${linkname}" ]; then
                ln -s "${latestfile}" "${LINKDIR}/${linkname}"
            fi
        fi
    done

    ## Remove old files
    OLDFILES="$(find "${FILEDIR}/" -maxdepth 1 -name "*.jar" -type f)"
    for of in ${OLDFILES}; do
        ## extract filename
        filename="$(basename -- "${of}")"
        plugin="${filename%.*}"
        plugin="$(echo "${plugin}" | sed 's/\-latest//g' | sed -e 's/[0-9].*$//g' | sed 's/\-v$//g'| sed 's/\.v$//g' | sed 's/\-$//g' | sed 's/\.$//g')"
        ## find latest file in filedir
        latestfile="$(ls -rv "${FILEDIR}/${plugin}"*.jar | head -n1)"
        if [ "${of}" != "${latestfile}" ]; then
            mv "${of}" "${FILEDIR}/.~outdated~/${filename}"
        fi
    done

    ## Update symlinks
    SYMLINKS="$(find "${LINKDIR}/" -maxdepth 1 -name "*.jar" -type l)"      # use l for symlinks
    for sl in ${SYMLINKS}; do
        ## extract filename
        filename="$(basename -- "${sl}")"
        plugin="${filename%.*}"
        plugin="$(echo "${plugin}" | sed 's/-latest//g' | sed -e 's/[0-9].*$//g' | sed 's/\-v$//g'| sed 's/\.v$//g' | sed 's/\-$//g' | sed 's/\.$//g')"
        ## find latest file in filedir
        latestfile="$(ls -rv "${FILEDIR}/${plugin}"*.jar | head -n1)"
        ## update symlink in linkdir
        linkname="$(basename -- "${latestfile}")"
        if [ "${sl}" != "${LINKDIR}/${linkname}" ]; then
            rm "${sl}"
            if [ -L "${LINKDIR}/${linkname}" ]; then
                rm "${LINKDIR}/${linkname}"
            fi
            if [ ! -L "${LINKDIR}/${linkname}" ]; then
                ln -s "${latestfile}" "${LINKDIR}/${linkname}"
            fi
        fi
    done

    ### End: Update plugin symlinks

    ## make sure cache dir exits
    if [ ! -d /var/cache/dmx ]; then
        mkdir /var/cache/dmx
    fi

    ## Set permissions
    chmod 750 /etc/dmx
    chmod 640 /etc/dmx/config.properties
    chmod 640 /etc/dmx/logging.properties
    chmod 750 /var/log/dmx
    chown root:dmx /etc/dmx
    chown root:dmx /etc/dmx/config.properties
    chown root:dmx /etc/dmx/logging.properties
    chown dmx:dmx /var/lib/dmx
    chown dmx:dmx /var/lib/dmx/dmx-db
    chown dmx:dmx /var/lib/dmx/dmx-filedir
    chown dmx:dmx /var/cache/dmx
    chown dmx:dmx /var/log/dmx
    
    ## enable the service if not enabled
    if [ "$(systemctl is-enabled dmx.service)" = "masked" ]; then
        deb-systemd-invoke unmask dmx.service >/dev/null || true
    fi
    if [ ! "$(systemctl is-enabled dmx.service)" ]; then
        deb-systemd-invoke enable dmx.service >/dev/null || true
    fi
    ## try to restart DMX if it is running
    if [ "$(systemctl is-active dmx.service)" ]; then
	deb-systemd-invoke restart dmx.service >/dev/null || true
    fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
